### ISSUE TITLE
Scroll out effect into header

### ISSUE THREAD

**Issue by Treadstudio** [markendley/soda#7]
on large breakpoint - see below screenshot. the panel should only be the width of the menu and it should sit into the header a little more. that'll give more of an effect. bit lost on LBP at the moment.

![Screenshot 2023-07-03 14 44 52](https://github.com/markendley/soda/assets/90736622/e2be7f06-d4df-401b-9e29-43d99eada1dc)

**Comment by markendley** [comment]
this is a tricky one because all I'm doing is scaling that white box (and everything in the white box) by a percentage.

the scale (the percentage) is based on the scroll position (as you scroll, the website calculates the scale % of the white box based on the scroll position).

would you settle for the white box just scaling up once the user scrolls past a certain point?

**Comment by Treadstudio** [comment]
this was where the idea came from...https://www.apeel.com/impact not sure if that helps?

**Comment by markendley** [comment]
Oh of course

The way I can fix this is just by getting rid of the max-width

**Comment by Treadstudio** [comment]
something has broken by that update....i'll take a vid and chat to you about it tomorrow.

i think we need to go back to what we had and readdress

**Comment by markendley** [comment]
following our phone conversation, I managed to accomplish it

except for the really large breakpoints

because I've realized the minimum I can go is 70%

any narrower than that, I start having complciations
